# Generated by Django 2.1.3 on 2018-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=96)),
                ('regist_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_login_datetime', models.CharField(max_length=24, null=True)),
                ('login_numbers', models.IntegerField(null=True)),
            ],
        ),
    ]
