# Generated by Django 2.1.3 on 2019-01-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20181225_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
